#!/usr/bin/env node
/**
 * Build Helix image, tag for a registry, optionally push, render sidecar YAML.
 *
 *   HELIX_IMAGE_REGISTRY=ghcr.io/example   (required for tag/push)
 *   HELIX_IMAGE_NAME=helix                 (default)
 *   HELIX_IMAGE_TAG=dev                    (default: local timestamp)
 *   HELIX_IMAGE_PUSH=1                     (docker push)
 *   HELIX_K8S_CLUSTER=1                    (kubectl apply rendered YAML — needs cluster)
 *
 * Tokens: K8S_PUSH_OK | K8S_PUSH_SKIP
 */
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registry = (process.env.HELIX_IMAGE_REGISTRY || '').replace(/\/$/, '');
const name = process.env.HELIX_IMAGE_NAME || 'helix';
const tag =
  process.env.HELIX_IMAGE_TAG ||
  process.env.GITHUB_SHA?.slice(0, 12) ||
  `local-${new Date().toISOString().replace(/[:.]/g, '').slice(0, 15)}`;
const doPush = process.env.HELIX_IMAGE_PUSH === '1' || process.env.HELIX_IMAGE_PUSH === 'true';
const doCluster =
  process.env.HELIX_K8S_CLUSTER === '1' || process.env.HELIX_K8S_CLUSTER === 'true';

function run(cmd, args, timeout = 600_000) {
  return spawnSync(cmd, args, { cwd: root, encoding: 'utf8', timeout });
}

const docker = run('docker', ['version'], 15_000);
if (docker.status !== 0) {
  console.log('K8S_PUSH_SKIP (docker not available)');
  process.exit(0);
}

if (!registry) {
  console.log(
    'K8S_PUSH_SKIP (set HELIX_IMAGE_REGISTRY=ghcr.io/org to tag/push; image build still via k8s-image-smoke)',
  );
  process.exit(0);
}

const image = `${registry}/${name}:${tag}`;
console.log(`=== docker build -t helix:local + tag ${image} ===`);
const build = run('docker', ['build', '-t', 'helix:local', '.'], 600_000);
if (build.status !== 0) {
  console.error(build.stderr || build.stdout || 'build failed');
  process.exit(build.status ?? 1);
}
const tagged = run('docker', ['tag', 'helix:local', image], 30_000);
if (tagged.status !== 0) {
  console.error(tagged.stderr || tagged.stdout);
  process.exit(tagged.status ?? 1);
}

if (doPush) {
  console.log(`=== docker push ${image} ===`);
  const push = run('docker', ['push', image], 600_000);
  if (push.status !== 0) {
    console.error(push.stderr || push.stdout);
    process.exit(push.status ?? 1);
  }
}

const srcYaml = path.join(root, 'deploy', 'k8s', 'helix-sidecar.yaml');
const outYaml = path.join(root, 'deploy', 'k8s', 'helix-sidecar.rendered.yaml');
let yaml = fs.readFileSync(srcYaml, 'utf8');
yaml = yaml.replace(/image:\s*helix:local\b/, `image: ${image}`);
yaml =
  `# Generated by scripts/k8s-push.mjs — do not edit; image=${image}\n` + yaml;
fs.writeFileSync(outYaml, yaml);
console.log(`Wrote ${path.relative(root, outYaml)}`);

if (doCluster) {
  const kubectl = run('kubectl', ['version', '--client'], 15_000);
  if (kubectl.status !== 0) {
    console.error('HELIX_K8S_CLUSTER=1 but kubectl not available');
    process.exit(1);
  }
  console.log('=== kubectl apply -f deploy/k8s/helix-sidecar.rendered.yaml ===');
  const apply = run('kubectl', ['apply', '-f', outYaml], 120_000);
  process.stdout.write(apply.stdout || '');
  if (apply.status !== 0) {
    console.error(apply.stderr || 'kubectl apply failed');
    process.exit(apply.status ?? 1);
  }
}

console.log(`K8S_PUSH_OK image=${image} push=${doPush} cluster=${doCluster}`);
